import "@/styles/index.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <h1>header</h1>
      <body>{children}</body>
      <h1>footer</h1>
    </html>
  );
}
