import type { Metadata } from "next";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { Suspense } from "react";

// 직접 생성하여 선언
// export const metadata: Metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

// 함수를 통해 생성하여 선언
export function generateMetadata(): Metadata {
  // 비동기 통신의 결과를 메타데이터의 정보로 활용할 수 있다.
  return {
    title: "Next.js",
    description: "Generated by Next.js",
  };
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <Suspense fallback={<div>Loading...</div>}>
          <Header />
        </Suspense>
        {children}
        <Footer />
      </body>
    </html>
  );
}
